application:
  config-server-base-url: http://localhost:8888

spring:
  config:
    import: optional:configserver:${application.config-server-base-url}
  cloud:
    config:
      uri: ${application.config-server-base-url}
      name: task-server
      profile: default
      fail-fast: true
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2
        max-interval: 5000
